--[[ TARDIS -- shared configuration.

    Everything the mod hard-codes about the world lives here: where the
    interior is parked, which decks there are, and what gets stocked into
    the containers. The decks themselves -- every wall, door and fitting --
    are TARDIS_Layout.lua, generated from BuildingEd (INTERIOR.md).

    Item ids come from media/scripts/generated/items/ for build 42.20.
]]

TARDIS = TARDIS or {}

local C = {}
TARDIS.Config = C

C.Version   = "2.0.1"
C.StateKey  = "TARDIS_State_v1"
C.ModPrefix = "[TARDIS]"

-- Bumped whenever the builder changes in a way every deck needs. A deck is
-- also brought up to date whenever its layout changes (TARDIS_Layout's
-- L.rev), the next time the player stands on it; the update preserves
-- furniture, stored items and crops. Revision 16 is the first built from
-- TARDIS_Layout (C.LayoutRev).
C.BuildRev = 16

-- Radius, in tiles, of the field that holds the dead back from the doors.
C.FieldRadius = 10

-- Flip to true for verbose build logging in console.txt.
C.Debug = false


---------------------------------------------------------------------------
-- Where the interior lives
---------------------------------------------------------------------------
-- Build 42 cells are 256 squares and vanilla ships cells out to x=77. The
-- Fifth-Wheel RV interior squats on cell 85,40. Cell 92,40 is clear of both,
-- and its y stays under 12000 so it also falls outside the unbounded
-- (x>22500 and y>12000) exit-menu test Project RV Interior applies.
C.InteriorCell = { x = 92, y = 40 }

-- Offset of the deck footprint inside that cell, so nothing touches a cell
-- edge; chunk seams make edge squares awkward to generate reliably.
C.RoomOffset = 16
C.RoomSize   = 25          -- outer footprint, walls included

-- Decks descend a z level at a time, but they are also stepped sideways so
-- that no deck ever sits directly above another.
--
-- This is the whole reason the interior is readable. Project Zomboid draws
-- every z level above the player and only hides the ones overhead when it
-- believes you are inside a building -- and "building" means room metadata
-- baked into a map lotheader, which runtime-generated squares cannot have.
-- Stacking the decks therefore left the top deck drawn over all the rest.
-- Nothing overhead means nothing to hide, so the renderer needs no
-- convincing. The descent through z is real; only the vertical alignment is
-- given up, and no camera angle can show that.
C.DeckSpacing = 80

-- How far beyond the footprint to strip the procedural wilderness the engine
-- grows in unmapped cells. Everything in this ring is removed down to bare
-- nothing, which renders as black void around the ship.
C.ClearMargin = 24

---------------------------------------------------------------------------
-- Decks, top to bottom
---------------------------------------------------------------------------
-- z 5 is the arrival deck and each deck below sits one level down.
C.TopZ = 5

-- col is the sideways step; z is the storey. Both descend together, so the
-- bottom deck sits on the ground at z 0 and the console room is five storeys
-- up, each one its own island.
--
-- What is *on* each deck -- rooms, walls, doors, floors, every fitting, where
-- a player lands and where the lamps hang -- is data, generated from the
-- BuildingEd files in design/buildinged/ into TARDIS_Layout.lua
-- (INTERIOR.md). Nothing here places anything.
C.Decks = {
    { id = "console", z = 5, col = 0, name = "Console Room" },
    { id = "housing", z = 4, col = 1, name = "Habitation Deck" },
    { id = "storage", z = 3, col = 2, name = "Stores Deck" },
    { id = "library", z = 2, col = 3, name = "Library Deck" },
    { id = "galley",  z = 1, col = 4, name = "Galley Deck" },
    { id = "growing", z = 0, col = 5, name = "Gardens" },
}

-- Positions are resolved in TARDIS_Util, which knows the engine cell size.

-- The first revision built from TARDIS_Layout. A deck stamped with anything
-- older was generated by the hand-placed octagonal builder, and is cleared
-- and refitted once (TARDIS_Build, refitLegacy) rather than rebuilt over.
C.LayoutRev = 16

-- Light for the deck lamps (TARDIS_Layout's `lamps`): r, g, b, radius. The
-- warm white of the console room's roundels.
C.DeckLight = { 1.0, 0.94, 0.82, 9 }

---------------------------------------------------------------------------
-- Items placed in the interior
---------------------------------------------------------------------------
-- The exterior shell is a world model, defined in media/scripts/tardis.txt.
C.ExteriorItem = "TARDIS.TARDISPoliceBox"

-- The console used to be a world item that opened like a crate. It is a
-- tile now -- the hexagonal console on the layout's `console` piece -- and
-- is itself a container, the head of the hold. Both old ids stay declared
-- in tardis.txt so a world that still has one can load it long enough for
-- the refit to lift it out and hand its contents to the hold.
C.ConsoleItem       = "TARDIS.TARDISConsoleUnit"
C.LegacyConsoleItem = "TARDIS.TARDISConsole"

-- The hold: the console and the roundel lockers of the console room, a
-- hundred apiece (a world object's container is capped at 100 by the engine,
-- ItemContainer.getCapacity). C.ConsoleKit is packed across them, in order,
-- the first time the console room is built.
C.HoldPieces = { console = true, hold_locker = true }

---------------------------------------------------------------------------
-- The sonic screwdriver
---------------------------------------------------------------------------
-- Right-click a locked door, gate, window or vehicle while carrying one and
-- the menu offers it (TARDIS_Sonic.lua, TARDISSonicAction): a short timed
-- action, and the lock gives way.
--
-- Two names for one item: the engine's inventory search compares the bare
-- type, while anything that spawns or places the item wants the full id.
C.SonicItem = "TARDIS.TARDISSonicScrewdriver"
C.SonicType = "TARDISSonicScrewdriver"

-- How close, in tiles, the player must be to use it without walking over
-- first. A little further than arm's length: it is a sonic screwdriver.
C.SonicReach = 3

-- How long the timed action takes, in the engine's action time units (moving
-- an item between containers is roughly 20-50): a lock, and a vehicle, which
-- gets its locks, ignition and battery seen to in the one go.
C.SonicLockTime    = 100
C.SonicVehicleTime = 200

-- The old behaviour, off by default: every lock within C.SonicRadius of the
-- carrier opening on its own, with no action from the player. Players asked
-- for the screwdriver to be something you use instead.
C.SonicAuto = false

-- How far that field reaches, in tiles, on the carrier's own level. Every
-- square inside it is examined on each sweep, so this is the number that
-- decides what a sweep costs; 15 is a good-sized house in every direction.
-- TARDIS_Sonic() from the debug console sweeps this far too.
C.SonicRadius = 15

-- What the field does to a vehicle once its doors are open. Unlocking alone
-- gets you into a car you still cannot drive, so the field also bypasses the
-- ignition and puts a charge in the battery.
--
-- Hotwiring is what the game itself gates "Start Engine" on. The battery is
-- separate and worth its own switch: most abandoned cars are flat, and a
-- hotwired car with a dead battery still does nothing at all.
--
-- Neither touches fuel. An empty tank stays empty -- that is not a lock and
-- not an ignition, and a car that drives forever on nothing is a different
-- mod.
C.SonicHotwire   = true
C.SonicJumpStart = true

-- With C.SonicAuto, sweeps run when the carrier steps onto a new square, and otherwise no more
-- often than this many ticks apart, so standing still is nearly free.
C.SonicInterval = 120

-- How many screwdrivers the sonic case beside the console doors holds.
C.SonicCount = 3

C.Loot = {}

C.Loot.tools = {
    "Base.Hammer", "Base.Saw", "Base.Screwdriver", "Base.Wrench",
    "Base.PipeWrench", "Base.Crowbar", "Base.Axe", "Base.HandAxe",
    "Base.Shovel", "Base.MasonsTrowel", "Base.Sledgehammer", "Base.Scissors",
    "Base.DuctTape", "Base.Nails", "Base.Screws", "Base.Rope", "Base.Twine",
    "Base.Needle", "Base.Thread", "Base.Lighter", "Base.Torch", "Base.Battery",
    "Base.Extinguisher", "Base.Sheet",
}

C.Loot.weapons = {
    "Base.Axe", "Base.BaseballBat", "Base.Machete", "Base.Katana",
    "Base.Crowbar", "Base.Shotgun", "Base.Pistol", "Base.VarmintRifle",
    "Base.HuntingRifle",
}

C.Loot.ammo = {
    "Base.ShotgunShells", "Base.Bullets9mm", "Base.Bullets9mmBox",
    "Base.Bullets38", "Base.Bullets44",
}

C.Loot.medical = {
    "Base.Bandage", "Base.Antibiotics", "Base.Pills", "Base.Disinfectant",
    "Base.FirstAidKit", "Base.PillsVitamins", "Base.PillsBeta",
    "Base.PillsSleepingTablets", "Base.AlcoholBandage",
}

C.Loot.food = {
    "Base.Bread", "Base.Cheese", "Base.Butter", "Base.Flour2", "Base.Sugar",
    "Base.Rice", "Base.Pasta", "Base.Salt", "Base.Potato", "Base.Carrots",
    "Base.Onion", "Base.Tomato", "Base.Egg", "Base.Milk", "Base.Steak",
    "Base.Chicken",
}

C.Loot.cookware = {
    "Base.Pan", "Base.Pot", "Base.Saucepan", "Base.Bowl", "Base.BreadKnife",
    "Base.ButterKnife", "Base.CheeseGrater",
}

C.Loot.seeds = {
    "Base.CarrotSeed", "Base.PotatoSeed", "Base.CabbageSeed",
    "Base.TomatoSeed", "Base.BroccoliSeed", "Base.CornSeed",
    "Base.OnionSeed", "Base.BasilSeed", "Base.ChivesSeed",
}

C.Loot.media = { "Base.VHS_Home", "Base.VHS_Retail" }

---------------------------------------------------------------------------
-- The armoury
---------------------------------------------------------------------------
-- Every firearm the build ships, every magazine, every calibre in every
-- packaging, the optics to go on them, and somewhere to hang a pistol.
--
-- The lists are split by what a crate is *for* rather than by what an item
-- is, because a container has a weight capacity and AddItems drops the
-- overflow in silence once it is reached. A military crate holds 50, a
-- locker 40, a set of metal shelves 30, and the numbers beside each list
-- below are what one copy of it weighs, straight out of
-- media/scripts/generated/items. Anything heavier than its crate never lands
-- whole, which is how an armoury meant to hold every calibre used to end up
-- short of 5.56 and .45.
--
-- Cartons are the reason for most of the splitting: one carton of .44 weighs
-- twelve, which is a quarter of a crate on its own.

C.Loot.handguns = {                                             -- 9.7
    "Base.Pistol", "Base.Pistol2", "Base.Pistol3",
    "Base.Revolver", "Base.Revolver_Long", "Base.Revolver_Short",
}

-- Not a firearm, but it belongs in the same crate: what you reach for when
-- the shooting is a bad idea.
C.Loot.katanas = { "Base.Katana" }                              -- 2.0

C.Loot.sidearms = {}                                            -- 11.7

C.Loot.longarms = {                                             -- 42.0
    "Base.Shotgun", "Base.ShotgunSawnoff",
    "Base.DoubleBarrelShotgun", "Base.DoubleBarrelShotgunSawnoff",
    "Base.VarmintRifle", "Base.HuntingRifle",
    "Base.AssaultRifle", "Base.AssaultRifle2",
    "Base.MSR7T_Rifle", "Base.JS14_Rifle", "Base.L94_Rifle",
}

-- Every gun in the build, for the wall racks. The crates take the two halves
-- above separately; 42 of longarms is already most of a crate.
C.Loot.firearms = {}

C.Loot.gunMags = {                                              -- 1.2
    "Base.9mmClip", "Base.44Clip", "Base.45Clip",
    "Base.556Clip", "Base.M14Clip", "Base.JS14_Clip",
}

-- Loose rounds and boxes: light enough that a shelf or a locker can carry a
-- spread of them.
C.Loot.pistolAmmo = {                                           -- 4.91
    "Base.Bullets9mm", "Base.Bullets9mmBox",
    "Base.Bullets38", "Base.Bullets38Box",
    "Base.Bullets44", "Base.Bullets44Box",
    "Base.Bullets45", "Base.Bullets45Box",
    "Base.Bullets357", "Base.Bullets357Box",
}

C.Loot.rifleAmmo = {                                            -- 3.38
    "Base.308Bullets", "Base.308Box",
    "Base.3030Bullets", "Base.3030Box",
    "Base.556Bullets", "Base.556Box",
    "Base.ShotgunShells", "Base.ShotgunShellsBox",
}

-- The bulk packaging, one crate each. A carton is twelve boxes.
C.Loot.pistolCartons = {                                        -- 48.0
    "Base.Bullets9mmCarton", "Base.Bullets38Carton",
    "Base.Bullets44Carton", "Base.Bullets45Carton",
    "Base.Bullets357Carton",
}

C.Loot.rifleCartons = {                                         -- 32.0
    "Base.308Carton", "Base.3030Carton", "Base.556Carton",
    "Base.ShotgunShellsCarton",
}

-- 5.56 on its own, because it is what the M16 (Base.AssaultRifle) and the
-- JS-14 both feed on and there is never enough of it. Two crates of this,
-- eight copies each: eight cartons is nearly two thousand rounds per crate,
-- and at 5.74 a copy the crate fills to 46 of its 50 without dropping any.
C.Loot.ammo556 = {                                              -- 5.74
    "Base.556Carton", "Base.556Box", "Base.556Bullets", "Base.556Clip",
}

-- What the shelves and lockers get: everything except the cartons, which are
-- too heavy to spread across furniture this size.
C.Loot.gunAmmo = {}

C.Loot.holsters = {                                             -- 2.2
    "Base.HolsterSimple", "Base.HolsterSimple_Black",
    "Base.HolsterSimple_Brown", "Base.HolsterSimple_Green",
    "Base.HolsterDouble", "Base.HolsterShoulder", "Base.HolsterAnkle",
    "Base.Holster_DuctTape", "Base.Holster_Hide",
}

C.Loot.attachments = {                                          -- 2.8
    "Base.x2Scope", "Base.x4Scope", "Base.x8Scope", "Base.RedDot",
    "Base.Laser", "Base.RecoilPad", "Base.ChokeTubeFull",
    "Base.ChokeTubeImproved",
}

-- The joined lists, built rather than written out twice so an id only ever
-- appears in one place.
local function appendTo(dest, ...)
    for _, list in ipairs({ ... }) do
        for _, id in ipairs(list) do table.insert(dest, id) end
    end
    return dest
end

appendTo(C.Loot.sidearms, C.Loot.handguns, C.Loot.katanas)
appendTo(C.Loot.firearms, C.Loot.handguns, C.Loot.longarms)
appendTo(C.Loot.gunAmmo, C.Loot.pistolAmmo, C.Loot.rifleAmmo)

---------------------------------------------------------------------------
-- What the console holds
---------------------------------------------------------------------------
-- A packing list rather than a loot list: explicit counts, put in once when
-- the console is first placed and never topped up again. This is the ship's
-- own store -- the thing you open before stepping out somewhere bad -- so it
-- is deliberately generous and deliberately finite.
--
-- The hold is the console and six roundel lockers, a hundred apiece. This
-- list is 679 items and 395 of weight, packed across them in order by
-- TARDIS_Build (packKit), which leaves room for the player's own things.
-- The kit is read back afterwards and anything that did not land is logged.
--
-- Weights, for arithmetic: a canned good is 0.8, a carton of 5.56 is 5, of
-- 9mm 8, of .44 12; bandages and pills are 0.1 to 0.2; rice and pasta are 2.
C.ConsoleKit = {
    -- to hand
    { "Base.Katana", 3 },
    { C.SonicItem, 3 },

    -- sidearms and what feeds them: the M9 for capacity, the Magnum for
    -- everything the M9 does not stop
    { "Base.Pistol", 2 },
    { "Base.Pistol3", 2 },
    { "Base.9mmClip", 4 },
    { "Base.44Clip", 4 },
    { "Base.Bullets9mmCarton", 3 },
    { "Base.Bullets44Carton", 2 },
    { "Base.HolsterSimple", 2 },
    { "Base.HolsterDouble", 2 },
    { "Base.HolsterShoulder", 2 },

    -- the M16, with six cartons and ten boxes of 5.56 behind it: a carton is
    -- twelve boxes of twenty, so this is a little under sixteen hundred
    -- rounds
    { "Base.AssaultRifle", 2 },
    { "Base.556Clip", 6 },
    { "Base.556Carton", 6 },
    { "Base.556Box", 10 },

    -- an infirmary in a drawer
    { "Base.Bandage", 100 },
    { "Base.AlcoholBandage", 50 },
    { "Base.Antibiotics", 50 },
    { "Base.Pills", 50 },
    { "Base.Disinfectant", 20 },
    { "Base.AlcoholWipes", 20 },
    { "Base.SutureNeedle", 20 },
    { "Base.SutureNeedleHolder", 2 },
    { "Base.Tweezers", 2 },
    { "Base.Splint", 5 },
    { "Base.CottonBalls", 10 },
    { "Base.FirstAidKit", 4 },
    { "Base.PillsVitamins", 20 },
    { "Base.PillsBeta", 10 },
    { "Base.PillsSleepingTablets", 10 },

    -- tins, and the one thing that makes tins food
    { "Base.TinOpener", 1 },
    { "Base.CannedBolognese", 15 },
    { "Base.CannedChili", 15 },
    { "Base.CannedCornedBeef", 15 },
    { "Base.CannedCorn", 15 },
    { "Base.CannedCarrots", 15 },
    { "Base.CannedPeaches", 15 },
    { "Base.CannedFruitCocktail", 15 },
    { "Base.CannedMushroomSoup", 15 },
    { "Base.TinnedBeans", 15 },
    { "Base.TinnedSoup", 15 },
    { "Base.CannedPotato2", 15 },
    { "Base.CannedPeas", 15 },
    { "Base.CannedTomato", 15 },
    { "Base.CannedMilk", 15 },

    -- dry stores, which keep as long as the tins do
    { "Base.Rice", 10 },
    { "Base.Pasta", 10 },
    { "Base.Flour2", 5 },
    { "Base.Sugar", 5 },
    { "Base.Salt", 5 },
    { "Base.BeefJerky", 10 },
}

-- Every skill book line in the game; all five volumes of each are shelved.
C.SkillBookLines = {
    "Aiming", "Blacksmith", "Butchering", "Carpentry", "Carving", "Cooking",
    "Electrician", "Farming", "Fishing", "Foraging", "Husbandry", "Masonry",
    "Maintenance", "Mechanic", "Pottery", "Reloading", "Tailoring",
    "Trapping",
}

C.Loot.magazines = {
    "Base.Magazine", "Base.MagazineCrossword", "Base.MagazineWordsearch",
    "Base.Magazine_Art", "Base.Magazine_Business", "Base.Magazine_Car",
    "Base.Magazine_Cinema", "Base.Magazine_Crime", "Base.Magazine_Fashion",
    "Base.Magazine_Firearm", "Base.ComicBook", "Base.Book",
}

C.Loot.linen = { "Base.Sheet", "Base.Pillow" }

-- The Wardrobe: long coats, jumpers, a fedora and every stripe of scarf.
C.Loot.wardrobe = {
    "Base.Scarf_StripeRedWhite", "Base.Scarf_StripeBlueWhite", "Base.Scarf_StripeBlackWhite",
    "Base.Hat_Fedora", "Base.Jacket_LeatherBrown", "Base.Jacket_LeatherBlack",
    "Base.Jacket_NavyBlue", "Base.Jumper_PoloNeck", "Base.Jumper_VNeck",
    "Base.Shirt_FormalWhite", "Base.Jacket_Padded", "Base.Jacket_Black",
    "Base.Tie_BowTieFull", "Base.Trousers_Suit", "Base.Suit_Jacket", "Base.Shoes_Black",
}

---------------------------------------------------------------------------
-- What each fitting holds
---------------------------------------------------------------------------
-- By the piece a container is part of (TARDIS_Layout, the fifth field of an
-- object), and the deck it is on: C.Stock[deck][piece] first, then
-- C.Stock.any[piece]. `loot` names a C.Loot list ("books" is every volume of
-- every skill book, built in TARDIS_Build); `amount` is how many picks from
-- it, and consecutive containers carry on through a list rather than all
-- starting at its top (U.stock). `cycle` hands each container of that piece
-- on the deck the next list in turn, so a storeroom's shelves alternate.
--
-- The armouries, the hold and the sonic case are packed rather than seeded,
-- and are handled by name in TARDIS_Build: see ARMOURY there.
C.Stock = {
    any = {
        bookcase        = { loot = "magazines", amount = 6 },
        gramophone      = { loot = "media", amount = 6 },
        pantry_dresser  = { loot = "food", amount = 10 },
        kitchen_counter = { loot = "cookware", amount = 4 },
        kitchen_sink    = { loot = "cookware", amount = 2 },
        fridge          = { loot = "food", amount = 12 },
        nightstand      = { loot = "linen", amount = 3 },
        wardrobe        = { loot = "linen", amount = 6 },
        clothes_rail    = { loot = "wardrobe", amount = 8 },
        writing_desk    = { loot = "magazines", amount = 4 },
        store_shelf     = { cycle = { "tools", "medical", "tools", "linen" }, amount = 10 },
        tool_locker     = { loot = "tools", amount = 10 },
        workbench       = { loot = "tools", amount = 8 },
        medical_cabinet = { loot = "medical", amount = 10 },
        seed_cabinet    = { loot = "seeds", amount = 10 },
        potting_bench   = { loot = "seeds", amount = 6 },
    },
    library = {
        bookcase = { loot = "books", amount = 8 },
    },
    housing = {
        wardrobe = { loot = "wardrobe", amount = 6 },
    },
    galley = {
        store_shelf = { loot = "food", amount = 10 },
    },
    growing = {
        store_shelf = { loot = "seeds", amount = 8 },
    },
}

---------------------------------------------------------------------------
-- Crops sown on the hydroponics deck
---------------------------------------------------------------------------
C.Crops = {
    "Potatoes", "Carrots", "Cabbages", "Tomato", "Broccoli", "Corn",
    "Radishes",
}

---------------------------------------------------------------------------
-- Travel
---------------------------------------------------------------------------
C.MaxBookmarks        = 40
C.LandingSearchRadius = 24   -- squares to spiral out from a chosen landing site

return C
